version: '3.8'

services:
  e4p:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - MAX_FILE_SIZE_MB=2048
      - MAX_CONCURRENCY=2
      - ARGON2_MEMORY_MB=256
      - ARGON2_TIME_COST=3
      - ARGON2_PARALLELISM=2
      - ARGON2_KEY_LEN=32
      - CLEAN_INTERVAL_MIN=5
      - FILE_TTL_MIN=60
      - DOWNLOAD_TOKEN_TTL_S=900
      - SECRET_KEY=${SECRET_KEY:-change_me_to_random_base64}
      - RATE_LIMIT_REQUESTS_PER_MINUTE=60
    volumes:
      - e4p_temp:/tmp/e4p
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  e4p_temp:
    driver: local
